### ISSUE TITLE
assignment submission

### ISSUE THREAD

**Issue by paulapanda** [abjer/sds#10]
Hi everyone,

I am logged on peergrade but I am not able to see where to submit assignment 1. 
I am not sure if one of my group members has uploaded it yet. Is there a way to check if the assignment has already been submitted?

Thanks,
Paula 

<img width="951" alt="screen shot 2018-08-19 at 4 58 14 pm" src="https://user-images.githubusercontent.com/42274007/44310356-b3d0cd00-a3d4-11e8-804f-69396b199477.png">

**Comment by madzac** [comment]
I am having the same issue as Paula.

**Comment by ztv764** [comment]
We have that problem too. They said it would be open from 2 pm. But nothing yet.  /Gr.30

**Comment by paulapanda** [comment]
Should we directly email Andreas or one of the other instructors?

**Comment by ztv764** [comment]
Maybe. You are very welcome to do that. Think that we are going to wait an hour or two to see if they open something.
But if you hear anything, Paula, please let us know. :)

**Comment by paulapanda** [comment]
I emailed Andreas. I will keep you posted if I hear anything.

**Comment by abjer** [comment]
Hi everyone, we will work out a solution ASAP - stay tuned. If we don't have it ready soon we will push back the deadline.

**Comment by paulapanda** [comment]
The assignment is open now. Thank you.

**Comment by abjer** [comment]
Yes, I will extend the hand-in deadline until tomorrow at 10.30am just in case anyone have had problems.
