### ISSUE TITLE
Vague questions

### ISSUE THREAD

**Issue by KarlTjensvoll** [abjer/sds#11]
Sometimes it would be nice with an extract or an example of the solution you want us to find, like: you should end up with strings that look like this: "string_example", or even a picture of a sample of the expected dataframe. For example this assignment:

`Ex. 8.2.1: Visit the https://www.trustpilot.com/ website and locate the categories page. From this page you find links to company listings. Get the category page using the requests module and extract each link to a specific category page from the HTML. This can be done using the basic python .split() string method. Make sure only links within the /categories/ section are kept, checking each string using the if 'pattern' in string condition. `

I then find the url https://www.trustpilot.com/categories/companies, which have links to company listings from the category page. Even after reading the question several times it was difficult to understand how I was going to proceed from here. After looking at the solution guide and reading the question again, I see that I misunderstood the crucial line `extract each link to a specific category page from the HTML`, and still I find it difficult to completely understand the assignment. After asking around I was not the only one with this issue, and this is not the first time it has been quite difficult understand exactly what an assignment asks from us, which is a source to a lot of frustration and an immense time sink.

In this exercise which is also quite difficult to get your head around, there seems that is should be an example, but is is sadly missing, even if I read the file directly from the repository:

`Ex. 7.2.13: Turn the dataset from wide to long so hourly data is now vertically stacked. Store this dataset in a dataframe called data. Name the column with hourly information hour_period. Your resulting dataframe should look something like this.`

**Comment by abjer** [comment]
Karl, thank you for pointing out the unclear and incorrect paragraphs. I have updated Ex. Set 7. Please direct us to other passages in the exercises (and lectures) that are vague or with some erroneous information when you find them, either here or by mail.
