### ISSUE TITLE
What does PolynomialFeatures do?

### ISSUE THREAD

**Issue by KarlTjensvoll** [abjer/sds#15]
I have some difficulties to completely understand what this function does.

$y = a*x_1 + b*x_2 + ...$

If i run this through PolynomialFeatures without sepcifying degrees, it will by default choose 2 degrees. Do we get out this:

$y = a*x_1^2 + b*x_2^2 ...$

or:

$y = a*x_1^2 + b*x_2*x_1 + ... + a*x_1*x_2 + b*x_2^2 + ...$

?

**Comment by kristianolesenlarsen** [comment]
They explain it in the first paragraph here: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html
