### ISSUE TITLE
When can we submit assignment 2?

### ISSUE THREAD

**Issue by Louisesrb** [abjer/sds#17]

**Comment by kristianolesenlarsen** [comment]
Peergrade should be open for submission until 23:59 today. If you cannot upload A2 please contact us so we can fix it.

**Comment by Louisesrb** [comment]
The page tells us that "YOU HAVE NO UPCOMING TASKS RIGHT NOW".

**Comment by kristianolesenlarsen** [comment]
It should work now. If not please open a new issue.
