### ISSUE TITLE
Some practical questions for the exam

### ISSUE THREAD

**Issue by ELaurents** [abjer/sds#27]
Should we write names, student ID's, or exam numbers on the project? 

The project has a maximum of 24 pages (normalsider). How do you measure a normalside with graphs for instance?

And how is the project graded? Should we write who did which parts of the project for an individual grade, or are we graded as a group?

**Comment by abjer** [comment]
I will get back to you ASAP on these details.

**Comment by ztv764** [comment]
Any news?

**Comment by ghost** [comment]
Bump

**Comment by abjer** [comment]
I just heard back from the study administration.

About putting your name on the front page it is up to you. For most of you we have a very good idea who you are from supervising you. No matter what you must your exam numbers on the front page. The exam numbers (or names) MUST show who contributed with writing which parts of the report. At most 20 pct. of the report can be written shared. If you fail to provide this the submission of your project may get rejected!

In terms page requirements then it is measured in normal pages corresponding to 2,400 characters per page. The count excludes figures, abstract, list of reference, frontpage, appendix etc.;  read more [here](https://samf.ku.dk/studenterservice/info_og_vejl/regleroglove/studieordninger/Rammestudieordning_SAMF_-_august_2018.pdf) under point 4.5. There are no requirements on spacing and margins but we recommend doing something standard like one and half spacing, 12 pt font, 3 cm margins everywhere.

**Comment by sarahkoelemij** [comment]
Since this is rather important information, especially with the contributions, maybe you should consider an announcement on Absalon to make sure everyone gets the message before deadline? :-)

**Comment by VictoriaHundevad** [comment]
But does your mail mean, that if we have handed in without saying who has written what, you'll figure it out? Or is our project at the risk of getting rejected?
