### ISSUE TITLE
Visualizing data in other programs 

### ISSUE THREAD

**Issue by naeimsamandari** [abjer/sds#29]
Are we allowed to visualize our data in other programs/codes than iPython and add them to the final exam paper?

Since time is limitted, using the knowledge we have of other programs for visualization, it would be very beneficial to use other programs, and then describe, document and add the plot to the paper.
We know that learning python/seaborn/matplot "the hard way" would be more beneficial for us in the long run, but for now we only have until saturday morning...

**Comment by abjer** [comment]
@Naeim-S we won't stop you from putting in figures made without Python into your paper. However, when we are grading we may deduct some points if it is not properly documented in the supporting Jupyter Notebook as we have asked you to have all relevant code there. Is that clear?
