### ISSUE TITLE
Link in excercise 6.2 does not work

### ISSUE THREAD

**Issue by KarlTjensvoll** [abjer/sds#5]
When i open https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data it says I am forbidden to open the link:

"Forbidden

You don't have permission to access /ml/machine-learning-databases/adult/adult.data on this server.

Apache/2.2.15 (CentOS) Server at archive.ics.uci.edu Port 443"

**Comment by kristianolesenlarsen** [comment]
it seems to be a problem with the UCI servers. Hopefully it will be fixed within a few hours, in the meantime you can get the same dataset from here: 

https://raw.githubusercontent.com/anyarcherty/Adult-Census-Income/master/census-income.data.csv

**Comment by snorreralund** [comment]
@Kristianuruplarsen: thank you for clarifying what adult.data was...
