### ISSUE TITLE
jobnet.dk excersise

### ISSUE THREAD

**Issue by ghost** [abjer/sds#6]
Any one who's response.text for the various url's (https://job.jobnet.dk/CV/FindWork?Offset=20&SortValue=BestMatch etc) DOES generate text that includes the links to various jobs that are actually shown on the webpage? Somehow they are excluded from the response.text.

**Comment by snorreralund** [comment]
the point of this exercise was not to find links, but instead to use the "hidden" API. So the response you get is actually all the data that you need about the jobposting.

**Comment by snorreralund** [comment]
oh but I see, you need to find the right link address to the hidden API, using the network monitoring tool.

**Comment by abjer** [comment]
@jansenjoost Did Snorre's answer here and perhaps in class resolve your question?
